apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: backend-scu-svc
  name: backend-scu-svc
spec:
  replicas: 4
  selector:
    matchLabels:
      run: backend-scu-svc
  template:
    metadata:
      labels:
        run: backend-scu-svc
    spec:
      containers:
      - image: vpstdacrus.azurecr.io/dotnet-daks-backend:0.3
        name: backend-scu-svc
        ports:
        - containerPort: 7000
      tolerations:
      - key: "BackendService"
        operator: "Equal"
        value: "ASR"
        effect: "NoSchedule"

---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: backend-scu-svc
  name: backend-scu-svc
spec:
  ports:
  - port: 7000
    protocol: TCP
    targetPort: 7000
  selector:
    run: backend-scu-svc
  type: ClusterIP
