apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: fe-wus2-scu-svc
  name: fe-wus2-scu-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      run: fe-wus2-scu-svc
  template:
    metadata:
      labels:
        run: fe-wus2-scu-svc
    spec:
      containers:
      - image: vpstdacrus.azurecr.io/dotnet-daks-frontend:0.2
        name: fe-wus2-scu-svc
        ports:
        - containerPort: 9000
        command: ["dotnet", "GrpcFrontend.dll"]
        args: ["-f", "0.0.0.0", "-p", "9000", "-b", "10.110.15.231", "-t", "7000"]

---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: fe-wus2-scu-svc
  name: fe-wus2-scu-svc
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    run: fe-wus2-scu-svc
  type: LoadBalancer
